### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Review by jonasraoni — CHANGES_REQUESTED** [review]
Hi @kant,

Could you please also translate the file "emailTemplates.xml"?

Thanks in advance!

**Comment by kant** [comment]
@jonasraoni emailtemplates.xml translated to spanish!

**Comment by asmecher** [comment]
(The PR for the Spanish translation of emailTemplates.xml was https://github.com/pkp/registrationNotification/pull/7)

**Comment by jonasraoni** [comment]
@asmecher feel free to merge as the other file is already in master =]

**Comment by asmecher** [comment]
Thanks -- also migrated everything to `po` format. Note that this makes the `master` branch compatible only with `3.2.x` or newer -- if you want to maintain a 3.1.x-compatible line, then I'd recommend creating a `stable-3_1_1` branch.

**Pull request merged**
